### ISSUE TITLE
0036-BRIE-event_queue.md

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1313] opened 2022-10-11 17:06 UTC
**Expand known filters regarding this AC**
Using configured external blockchain nodes, the Event Queue filters for specific events provided in GetSubscribedEventSourcesResponse

What is the param which controls this? - Event Queue retries sending events that have gone too long without being accepted ([0036-BRIE-006]

Can we include a diagram from core on how events are triggered/sent etc including all internal statuses

**Comment by gordsport** [comment] 2022-10-12 08:44
Closing as a duplicate of: 
- https://github.com/vegaprotocol/specs/issues/1173

I have added the above notes as tasks to be done as the other ticket is worked on

**Closed as completed by gordsport** 2022-10-12 08:44 UTC
